### ISSUE TITLE
orchestrator-host--functionKey not found in key vault

### ISSUE THREAD

**Issue by hkamel** [Azure/GPT-RAG#79]
Is the template exected to add the orchestrator-host--functionKey to the key vault or this step is expected to be manually after the deployment?

![image](https://github.com/Azure/GPT-RAG/assets/5002831/64b30ff2-7ff0-4c11-a3b5-d21e3339573b)

**Comment by bgawale** [comment]
@hkamel that's right - noticed the same issue and had to add the secret manually. It appears that the issue has been closed already, but do not find any comments for it. 
https://github.com/Azure/GPT-RAG/issues/45

**Comment by framigni** [comment]
Hi @bgawale would you be so kind to tell me how to do that, I'm not familiar with the process

**Comment by framigni** [comment]
> Hi @bgawale would you be so kind to tell me how to do that, I'm not familiar with the process

Thanks, solved ! The secret to add to the key vault _secrets_ is the **_master** key in the _fnorch0-pp74jmspzstpu_ Function App.

**Comment by gbecerra1982** [comment]
There is a bug when the azure functions some times is created and is not generated the Key until we don't browse the keys in the function that's the reason, we already reported to the Product Group team, in order to solve once the infrastructure is created browse both funtions and make sure that they are added into the keyvault.
