### ISSUE TITLE
How to upload a new document?

### ISSUE THREAD

**Issue by vinc1am** [Azure/GPT-RAG#93]
Thanks for this repo. As per title, may I know how to upload the document? I have uploaded the document (pdf) in the document folder, but I assume we need to use indexer to chunk, reindex and embed the documents? Could anyone give me a simple guideline for this. Thanks soooo much for the help.

**Comment by hamzaawan99** [comment]
Please check #92 and #96

**Comment by gbecerra1982** [comment]
Hello vinc1am, 

You will need to upload the document into the Storage Account Container "documents", once you have uploaad you can open the Search Service, Indexers and run both "[ragindex-indexer-chunk-documents]" this will generate the vectors and chunks, then run the following indexer [ragindex-indexer-chunk] in order to index the chunks. Once that i completed you should be able to consume the frontend.
