### ISSUE TITLE
Add source documents to object storage

### ISSUE THREAD

**Issue by paulmoise** [Azure/GPT-RAG#96]
Hi and thanks for this repo.

I would know where I have to upload my the pdf documents.

As they describe in the readme.

**4 Add source documents to object storage**

**Upload your documents to the documents folder in the storage account which name starts with strag.**

I identify the storage account starts with _strag_ then I go to _containers_ and upload my pdf file in _documents_ folder.

The problem is:
Everytime I run my front-end, and Ask question about the file it can't answer the question.

Can anyone give a help ?

**Comment by hamzaawan99** [comment]
The data ingestion function runs every 1 hour by default so documents will be ingested after one hour. You can change this behaviour in `infra/main.bicep` file line numbers 115-117
 
```
@description('Frequency of search reindexing. PT5M (5 min), PT1H (1 hour), P1D (1 day).')
@allowed([ 'PT5M', 'PT1H', 'P1D' ])
param searchIndexInterval string = 'PT5M'
```

Check after 5-10 minutes, if error persists, go to the data ingestion function app and check logs for `document_chucking`, there might be rate limit error on OpenAI models. In this case, go to OpenAI Studio and increase the TPM value for both models (especially text-embeddings)

You can check #92 as well

**Comment by paulmoise** [comment]
Hello and thank you for your answer.

Even if it doesn't help me to solve my issues.

What solves my issues is this.

1. After running the project as they describe in the readme, I understood that I have this issue because after uploading my pdf documents in the storage starting by **strag** the ingestion part it doesn't create the embedding.
2. Then I clone the ingestion repo. I run the setup script and fill in all the information about my Azure resources. It creates the embedding and I can see the process in my  _log stream_ on Azure.

Everythings work now.

Thank you

**Comment by maacaro** [comment]
Hello,

I'm encountering an issue with the ingestion function in the GPT-RAG project; it doesn't seem to initiate as expected. I've meticulously followed the steps outlined in the README file:

1. Initialized the project with azd init -t azure/gpt-rag.
2. Logged in with azd auth login.
3. Deployed the project using azd up.
4. Uploaded the source documents to the specified object storage, ensuring that they are placed in the 'documents' folder of the storage account whose name begins with 'strag'.

However, even after waiting for a couple of hours, it appears that the ingestion function has not been triggered. Consequently, the index and indexer are absent, and I'm unable to retrieve answers from my uploaded data.

I would greatly appreciate any guidance or suggestions on how to resolve this issue. Thank you for your time and assistance.

**Comment by hamzaawan99** [comment]
@maacaro I had the same issue. I initialized the project in a new directory and commented the lines 221 and 233 in `setup.py` of `gpt-rag-ingestion` repo. Then deployed the application and it the indexers and indexes were created and ingestion started to work.

**Comment by framigni** [comment]
> @maacaro I had the same issue. I initialized the project in a new directory and commented the lines 221 and 233 in `setup.py` of `gpt-rag-ingestion` repo. Then deployed the application and indexers and indexes were created and ingestion started to work.

@hamzaawan99 I'm having the same issue, but wondering if, rather than re-deploying everything, we need just to add an Import and Vectorize Data on search0-pp74jmspzstpu, pointing to the Documents container

**Comment by hamzaawan99** [comment]
@framigni You could update the AI search with vectorizer instead of a new deployment. I only created a deployment to see if there are any other issues.

**Comment by framigni** [comment]
Well, I'm not out of the woods yet. The documents are successfully indexed, and the re-indexing is scheduled for every 5 minutes. But the Chat is still responding "I don't have enough information". It's probably because the document_chunking function has 0 execution count and no logs, so it's not been triggered. I wonder what triggers the function to run and if it can be forced,

**Comment by framigni** [comment]
> Hello and thank you for your answer.
> 
> Even if it doesn't help me to solve my issues.
> 
> What solves my issues is this.
> 
> 1. After running the project as they describe in the readme, I understood that I have this issue because after uploading my pdf documents in the storage starting by **strag** the ingestion part it doesn't create the embedding.
> 2. Then I clone the ingestion repo. I run the setup script and fill in all the information about my Azure resources. It creates the embedding and I can see the process in my  _log stream_ on Azure.
> 
> Everythings work now.
> 
> Thank you

sorry, @paulmoise , I'm having the same issue and trying to replicate your solution. After you cloned the Ingestion repo, did you` azd deploy `or run the `setup.py` ?

**Comment by paulmoise** [comment]
Hello, @framigni.

1. Run setup.py file and file all the information about your Azure resources

Enter subscription ID: 
Enter resource group:
Enter chunking function app name: <something_start_by> _fninges_
2. Then  go to your Search service <the name should start by _search_ >. 
  Go to **indexers** on the left panel.
  Click on **ragindex-indexer-chunk-documents**  and click on **Run**

**Comment by maacaro** [comment]
Hello @paulmoise,

I am encountering an issue when executing the `setup.py` file. The following error messages are generated:

```
2024-01-23 10:32:47,112 - ERROR - Error when calling search API put datasources ragindex-datasource. Code: 403
2024-01-23 10:32:47,112 - ERROR - Error when calling search API Reason: Forbidden
2024-01-23 10:32:47,112 - ERROR - Error when calling search API put datasources ragindex-datasource. Message: Authorization failed.
```

It appears to be a problem related to authorization. Have you ever encountered this error, or do you have any insights on how to resolve it?

Thank you for your assistance.

Best regards,

**Comment by paulmoise** [comment]
@maacaro 

I didn't encounter this issue but did you run `az login` to login to azure before ?

**Comment by maacaro** [comment]
Hello @paulmoise, @framigni, I've done the following changes in the setup.py and it worked for me:

1. I commented out line 39:
   ```python
   # "Authorization": f"Bearer {token}",
   ```

2. I then inserted my API key on line 41:
   ```python
   'api-key': 'xxxxx'
   ```

After making these adjustments, the script executed successfully and created the following components:

- Datasources blob
- Indexes
- Skillsets
- Indexers

I hope this information might be helpful to others facing similar issues.

**Comment by framigni** [comment]
Hi @maacaro 
I'm having problems running setup.py (On Windows/Powershell, with Python version 3.12.1).  It exits with message:

> Traceback (most recent call last):
>   File "C:\Windows\System32\gpt-rag-ingestion\setup.py", line 3, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'

**Comment by framigni** [comment]
@maacaro @paulmoise 
yes, it's working. My problem was my Python environment was not up to scratch. Then finally setup.py created the proper Search Index and the Ingest function kicked off. Chat now responding as expected.
Thanks for all your help, appreciated

**Comment by placerda** [comment]
@hamzaawan99 @maacaro @paulmoise  and @framigni  thank your for your assistance resolving this issue.  If you have any more questions, feedback, or need further assistance, feel free to ask. I'm leaving a comment here to better explain some aspects of the deployment of the ingestion component and creation of AI Search elements, so it can help with future deployments.
   
"azd up" executes the setup.py file through a [postdeploy hook](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-extensibility) that is executed after deploying the ingestion function, as defined in the [azure.yaml](https://github.com/Azure/GPT-RAG/blob/main/azure.yaml) file of the template.  
   
The setup.py file uses [DefaultAzureCredential](https://github.com/Azure/gpt-rag-ingestion/blob/d4b7629901a9d9bda57b52bedf1f9fc5ccee7577/setup.py#L210) to configure AI Search. DefaultAzureCredential looks for an available identity in the environment according to a [predefined order](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential). Ideally, the identity used by DefaultAzureCredential is the same one used by "azd auth login" so that the setup can connect to the services provisioned with "azd".  
   
The setup.py file will create all the necessary components for indexing (containers, datasources, index, skillset and indexer). The indexer, that will index the files in the documents container. After the setup.py file finishes, the indexer will be automatically executed and scheduled to run every 1 hour. It can also be manually executed through the "Run" option in the indexers tab of the AI Search service.  
   
If the services in Azure have been provisioned and you want to redeploy only the ingestion component, you can do this by cloning the "gpt-rag-ingestion" repository and following these steps with "azd":  
   
1. Run "azd auth login"
2. Run "azd env refresh" (using the same parameters used in the original deployment) 
3. Run "azd deploy"

Paulo
